# Generated by Django 4.1.12 on 2023-12-01 20:49

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_comment_image_delete_olduser_comment_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='image',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
